//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesajlasmaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullaniciTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullaniciTbl()
        {
            this.mesajTbl = new HashSet<mesajTbl>();
            this.mesajTbl1 = new HashSet<mesajTbl>();
        }
    
        public int id { get; set; }
        public string isim { get; set; }
        public string soyad { get; set; }
        public string mail { get; set; }
        public string sifre { get; set; }
        public string yetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesajTbl> mesajTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesajTbl> mesajTbl1 { get; set; }
    }
}
