//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesajlasmaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesajTbl
    {
        public int mesajId { get; set; }
        public int mesajiAtanId { get; set; }
        public int mesajiAlanId { get; set; }
        public string mesajIcerik { get; set; }
        public System.DateTime mesajTarih { get; set; }
    
        public virtual kullaniciTbl kullaniciTbl { get; set; }
        public virtual kullaniciTbl kullaniciTbl1 { get; set; }
    }
}
